name: checks

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies from the lockfile
        run: npm ci
      - name: Run internal checks
        run: npm run check
